"""Création initiale avec modèle Client mis à jour

Revision ID: 58af6f64a5ce
Revises: 
Create Date: 2025-05-26 11:23:35.444586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58af6f64a5ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=200), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('ip_router', sa.String(length=50), nullable=True),
    sa.Column('ip_antea', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('intitule', sa.String(length=200), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id_operateur', sa.Integer(), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_operateur'], ['operateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident')
    op.drop_table('operateur')
    op.drop_table('client')
    # ### end Alembic commands ###
