"""Ajout table etat pour États IA

Revision ID: 20250801_133000
Revises: 2adc92440c6c
Create Date: 2025-08-01 13:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20250801_133000'
down_revision = '2adc92440c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('type_etat', sa.String(length=50), nullable=False),
    sa.Column('periode_debut', sa.Date(), nullable=True),
    sa.Column('periode_fin', sa.Date(), nullable=True),
    sa.Column('contenu_ia', sa.Text(), nullable=True),
    sa.Column('graphiques_data', sa.JSON(), nullable=True),
    sa.Column('parametres', sa.JSON(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('utilisateur', sa.String(length=100), nullable=True),
    sa.Column('hash_cache', sa.String(length=64), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Créer les index pour optimiser les performances
    op.create_index(op.f('ix_etat_titre'), 'etat', ['titre'], unique=False)
    op.create_index(op.f('ix_etat_type_etat'), 'etat', ['type_etat'], unique=False)
    op.create_index(op.f('ix_etat_periode_debut'), 'etat', ['periode_debut'], unique=False)
    op.create_index(op.f('ix_etat_periode_fin'), 'etat', ['periode_fin'], unique=False)
    op.create_index(op.f('ix_etat_statut'), 'etat', ['statut'], unique=False)
    op.create_index(op.f('ix_etat_hash_cache'), 'etat', ['hash_cache'], unique=False)
    op.create_index(op.f('ix_etat_date_creation'), 'etat', ['date_creation'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Supprimer les index
    op.drop_index(op.f('ix_etat_date_creation'), table_name='etat')
    op.drop_index(op.f('ix_etat_hash_cache'), table_name='etat')
    op.drop_index(op.f('ix_etat_statut'), table_name='etat')
    op.drop_index(op.f('ix_etat_periode_fin'), table_name='etat')
    op.drop_index(op.f('ix_etat_periode_debut'), table_name='etat')
    op.drop_index(op.f('ix_etat_type_etat'), table_name='etat')
    op.drop_index(op.f('ix_etat_titre'), table_name='etat')
    
    # Supprimer la table
    op.drop_table('etat')
    # ### end Alembic commands ###