"""Ajout des champs ip_router et ip_antea au modèle Client

Revision ID: 2adc92440c6c
Revises: 
Create Date: 2025-05-26 11:21:53.057092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adc92440c6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        # Renommer contact en telephone
        batch_op.alter_column('contact',
               new_column_name='telephone',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('ip_router',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('ip_antea',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        # Renommer telephone en contact
        batch_op.alter_column('telephone',
               new_column_name='contact',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('ip_antea',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('ip_router',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###
